### ISSUE TITLE
用上namespace吧

### ISSUE THREAD

**Issue by picasso250** [actrace/chnstyle#1]
PHP5.4已经支持function放在 namespace里了。

**Comment by actrace** [comment]
命名空间实际上会让某些问题变复杂,暂不考虑.

**Comment by picasso250** [comment]
命名空间实际上会让代码变得更有组织，除此之外，什么问题会变得复杂呢？你能否讲给我听听？

**Comment by actrace** [comment]
本计划面向初级程序员,因此任何不必要的负担都应该卸除.
往极端了点说,你可以用echo来完成hello world,也可以找一个框架来完成hello world.
这是我所想表达的两者之间的差异以及为什么不那么做,希望你能明白.
